### ISSUE TITLE
Error: GitHub Environment: Errors

### ISSUE THREAD

**Issue by ifyour** [andykenward/github-actions-cloudflare-pages#251]
When I deploy, the workflow gets the following [error](https://github.com/ifyour/hono-spa-app/actions/runs/8214433497/job/22466922072?pr=1):

```bash
Run unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566
  with:
    cloudflare-api-token: ***
    cloudflare-account-id: ***
    cloudflare-project-name: hono-spa-app
    directory: dist
    github-token: ***
    github-environment: hono-spa-app (Preview)

Error: GitHub Environment: Errors - [{"type":"NOT_FOUND","path":["repository","environment"],"locations":[{"line":4,"column":5}],"message":"Could not resolve to an Environment with the name hono-spa-app (Preview)."}]
file:///home/runner/work/_actions/unlike-ltd/github-actions-cloudflare-pages/8c09c46bd39321b4aa3784852491d9e4f09e1566/dist/index.js:2368
    throw new Error(`GitHub Environment: Not created for ${gitHubEnvironment}`);
          ^

Error: GitHub Environment: Not created for hono-spa-app (Preview)
```

My CI configuration details: https://github.com/ifyour/hono-spa-app/blob/dev/.github/workflows/deploy.yml

`GH_TOKEN` permission scope:

<img width="566" alt="image" src="https://github.com/unlike-ltd/github-actions-cloudflare-pages/assets/15377484/00822966-470f-45dc-ab3c-87ec7c924407">

**Comment by andykenward** [comment]
Have you created the GitHub environment called "hono-spa-app (Preview)"? See [Creating an environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment). You have to manually create the GitHub environments for the repo to use the GitHub Action. It is not part of the action, as the permissions required to [create a GitHub environment](https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28#create-or-update-an-environment) requires `adminstation:write`. Will update the README.md  and throw a better error with this information.

You also don't need to use a GitHub personal token. The GitHub Action has access to a [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) and will use the `permissions` defined in your workflow `.yml`file.

Sorry for the confusion.

**Comment by ifyour** [comment]
Thanks so much, problem solved, this Action is more powerful than the official one. Thank you for your efforts!

**Comment by ifyour** [comment]
Unfortunately, free accounts do not support private repository creation environments. Is there a configuration that supports turning off the environment option?

**Comment by andykenward** [comment]
> Unfortunately, free accounts do not support private repository creation environments. Is there a configuration that supports turning off the environment option?

Sorry, not at the moment. Using GitHub Environments is a core feature of this GitHub Action to save the deployment payload returned from a Cloudflare Pages deployment to a GitHub Deployment to be referenced later to delete the Cloudflare Pages & GitHub deployments.
