### ISSUE TITLE
Consider the GitHub environment when deleting deployments in a monorepo

### ISSUE THREAD

**Issue by chalkygames123** [andykenward/github-actions-cloudflare-pages#268]
When deploying for the production branch in a monorepo, this action tries to delete not only the deployments related to an app that is about to be deployed but also those that are not related, resulting in the following error and warning:

```
Error: Cloudflare API: The deployment ID you have specified does not exist. Update the deployment ID and try again.  [code: 8000009]
Warning: Cloudflare Deployment might have been deleted already: 10733085-bac8-442c-a403-b489cdfcfcef
```

In a workflow for deleting deployments, it is also currently difficult or impossible to determine the target GitHub environment (i.e., the [`jobs.<job_id>.environment`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) key value) and get its [environment-level configuration variables](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment).

Any chance these will be resolved?

My last attempts for your information: https://github.com/chalkygames123/sandbox-actions/actions/runs/8338818932

---

By the way, would you like to accept a small donation through a service like [GitHub Sponsors](https://github.com/sponsors) or [Buy Me a Coffee](https://www.buymeacoffee.com/)?

**Comment by andykenward** [comment]
>When deploying for the production branch in a monorepo, this action tries to delete not only the deployments related to an app that is about to be deployed but also those that are not related, resulting in the following error and warning:

Adding the `environment` to the GitHub REST API call when we get all the GitHub deployments might be needed then. We are currently only using the ref "branch".

See Draft PR change https://github.com/unlike-ltd/github-actions-cloudflare-pages/pull/269/files#diff-f472868db552c908824a53acb14feb64eebd5ea89cc77dcf0f122809eb8a08ba

**Comment by andykenward** [comment]
>In a workflow for deleting deployments, it is also currently difficult or impossible to determine the target GitHub environment (i.e., the [jobs.<job_id>.environment](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) key value) and get its [environment-level configuration variables](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment).

Will have to look into how to access a `jobs.<job_id>.environment` and its variables.

**Comment by andykenward** [comment]
> By the way, would you like to accept a small donation through a service like [GitHub Sponsors](https://github.com/sponsors) or [Buy Me a Coffee](https://www.buymeacoffee.com/)?

Perhaps. Need to look into those. I maintain this in my spare time to learn more about GitHub Actions & Cloudflare Pages API.

**Comment by andykenward** [comment]
@chalkygames123 Try [v1.3.1](https://github.com/unlike-ltd/github-actions-cloudflare-pages/releases/tag/v1.3.1) in your monorepo. It should now get GitHub deployments based on the git branch & GitHub Environment.

**Comment by chalkygames123** [comment]
Great, the first problem has been resolved as follows:

- https://github.com/chalkygames123/sandbox-actions/actions/runs/8369155558
- https://github.com/chalkygames123/sandbox-actions/actions/runs/8369155562

And I just sponsored you on GitHub Sponsors. Stay well, and keep coding!

**Comment by andykenward** [comment]
> Great, the first problem has been resolved as follows:
> 
> * https://github.com/chalkygames123/sandbox-actions/actions/runs/8369155558
> * https://github.com/chalkygames123/sandbox-actions/actions/runs/8369155562
> 
> And I just sponsored you on GitHub Sponsors. Stay well, and keep coding!

@chalkygames123 Thank you for the GitHub sponsor!

**Comment by andykenward** [comment]
>In a workflow for deleting deployments, it is also currently difficult or impossible to determine the target GitHub environment (i.e., the [jobs.<job_id>.environment](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) key value) and get its [environment-level configuration variables](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment).

@chalkygames123 you'll need a separate job for each environment deployment you want to delete. We can't access multiple environments and their secrets in one job.

**Comment by chalkygames123** [comment]
Thank you for investigating 🙏

Actually, the second problem was a typical [XY problem](https://xyproblem.info/). Ultimately, what I want to do is to omit specifying the `CLOUDFLARE_PROJECT_NAME` (and maybe the `CLOUDFLARE_ACCOUNT_ID`) input. Just an idea, but including its value in the GitHub Deployment payload might help?

**Comment by andykenward** [comment]
> Actually, the second problem was a typical [XY problem](https://xyproblem.info/). Ultimately, what I want to do is to omit specifying the `CLOUDFLARE_PROJECT_NAME` (and maybe the `CLOUDFLARE_ACCOUNT_ID`) input. Just an idea, but including its value in the GitHub Deployment payload might help?

We can add that to the GitHub Deployment payload. But I would have to change them from [required inputs](https://github.com/unlike-ltd/github-actions-cloudflare-pages/blob/132cec4a7402a114de6583d3cd44ea081a984ddb/action.yml#L12-L17). Perhaps we can support using `"*"` for certain inputs only for a deletion? But that seems verbose. Will look into adding validation for some inputs within the action when deploying, but ignored when deleting.

**Comment by chalkygames123** [comment]
Apparently, this is a good case for having a dedicated "sub-action," for example, as the official [upload-artifact](https://github.com/actions/upload-artifact) and [cache](https://github.com/actions/cache) actions do.

**Comment by andykenward** [comment]
> Apparently, this is a good case for having a dedicated "sub-action," for example, as the official [upload-artifact](https://github.com/actions/upload-artifact) and [cache](https://github.com/actions/cache) actions do.

Oh yes! Having a "sub-action" for the deletion would be better. And we can use the same repo.

**Comment by andykenward** [comment]
> Apparently, this is a good case for having a dedicated "sub-action," for example, as the official [upload-artifact](https://github.com/actions/upload-artifact) and [cache](https://github.com/actions/cache) actions do.

@chalkygames123 Try [2.0.0](https://github.com/unlike-ltd/github-actions-cloudflare-pages/releases/tag/v2.0.0). It saves a new payload and has a delete "sub-action".

**Comment by chalkygames123** [comment]
Hey, sorry for the late reply. I have been swamped lately.

I just tried the latest version today and confirmed that it works perfectly. Thank you very much!
