### ISSUE TITLE
Allow changing working directory for monorepo

### ISSUE THREAD

**Issue by chalkygames123** [andykenward/github-actions-cloudflare-pages#275]
To deploy Pages Functions, Wrangler must be run in the directory where the `functions/` directory lives, but the [`jobs.<job_id>.steps[*].working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) key cannot be used with the [`jobs.<job_id>.steps[*].uses`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses) key.

**Comment by andykenward** [comment]
Will have to add the `working-directory` when we call `wrangler` here https://github.com/unlike-ltd/github-actions-cloudflare-pages/blob/2e411d90281a8076b19eec26cb972368f3cac97e/src/cloudflare/deployment/create.ts#L49-L54 . 

We try to use the [jobs.<job_id>.steps[*].working-directory](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) over defining another [jobs.<job_id>.steps[*].with](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) input.

Perhaps need to validate the `working-directory` & `directory` exist. The [jobs.<job_id>.steps[*].working-directory](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) might do this for us?

**Comment by andykenward** [comment]
@chalkygames123 Can you not use [Advanced Mode](https://developers.cloudflare.com/pages/functions/advanced-mode/) for Pages Functions

>Advanced mode allows you to develop your Pages Functions with a _worker.js file rather than the /functions directory.

**Comment by andykenward** [comment]
@chalkygames123 try [`v1.3.2`](https://github.com/unlike-ltd/github-actions-cloudflare-pages/releases/tag/v1.3.2)

**Comment by chalkygames123** [comment]
Thank you, your fix does the trick: https://github.com/chalkygames123/sandbox-actions/actions/runs/8410156418

> Can you not use [Advanced Mode](https://developers.cloudflare.com/pages/functions/advanced-mode/) for Pages Functions

Technically, I can use Advanced mode but prefer directory mode when building an API for one specific app.
